###
GET http://localhost:8080

###
GET http://localhost:8080/api/employees

###
GET http://localhost:8080/api/employees/1

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Patrik",
  "email": "patriktomsic@gmail.com",
  "department": "tech",
  "activityStatus": true

}

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Antonija",
  "email": "sulaantonija@gmail.com",
  "department": "tech",
  "activityStatus": false

}

###
DELETE http://localhost:8080/api/employees/2

###
PATCH http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "name": "Antonija",
  "department": "sales",
  "activityStatus": true
}

###
PATCH http://localhost:8080/api/employees/1/activate
Content-Type: application/json


###
PATCH http://localhost:8080/api/employees/1/deactivate
Content-Type: application/json


###
POST http://localhost:8080/api/tickets?categoryId=1
Content-Type: application/json

{
  "title": "Ticket broj 1",
  "customerName": "Lara",
  "customerEmail": "laralara@gmail.com",
  "customerDescription": "Stranica ne reagira",
  "department": "tech",
  "priority": "HIGH",
  "status": "COMPLETED"
}

###
GET http://localhost:8080/api/tickets

###
DELETE http://localhost:8080/api/tickets/1

###
PATCH http://localhost:8080/api/tickets/1
Content-Type: application/json

{
  "title": "Sve isto ali drugi title"
}

###
GET http://localhost:8080/api/tickets?status=COMPLETED

###
GET http://localhost:8080/api/categories
###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Software",
  "description": "Software related issues",
  "activityStatus": true
}
###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Hardware",
  "description": "Hardware related issues",
  "activityStatus": false
}

###
DELETE http://localhost:8080/api/categories/1

###
PATCH http://localhost:8080/api/categories/1
Content-Type: application/json

{
  "description": "All software related issues",
  "activityStatus": false

}

###
PATCH http://localhost:8080/api/categories/1/deactivate
Content-Type: application/json


###
PATCH http://localhost:8080/api/categories/1/activate
Content-Type: application/json


###
GET http://localhost:8080/api/ticket-notes

###
GET http://localhost:8080/api/ticket-notes/2

###
POST http://localhost:8080/api/ticket-notes?employeeId=1&ticketId=1
Content-Type: application/json

{
  "text": "Tekst naseg notea koji pripada 1.employeeu na 1.ticket!"
}

###
DELETE http://localhost:8080/api/ticket-notes/3

###
PATCH http://localhost:8080/api/ticket-notes/1
Content-Type: application/json

{
  "text": "Promjenjen tekst"
}